name: Unzip Android Project

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Unzip project (auto-detect)
        run: |
          unzip bilalshare-android.zip
          PROJECT_DIR=$(ls -d */ | head -n 1)
          echo "Found project folder: $PROJECT_DIR"
          shopt -s dotglob
          mv "$PROJECT_DIR"* .
          rm -rf "$PROJECT_DIR"

      - name: Commit extracted files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Extract Android project"
          git push
